import 'package:flutter/material.dart';

/// 单据类型策略配置
/// 使用策略模式封装不同单据类型的差异
enum BillType {
  purchaseOrder(
    code: 'purchase_order',
    name: '采购订单',
    title: '新建采购订单',
    icon: Icons.shopping_cart,
    primaryColor: Color(0xFF2196F3),
    requiresPartner: true,
    requiresWarehouse: true,
    requiresAmount: true,
    partnerLabel: '供应商',
    warehouseLabel: '入库仓库',
    itemsLabel: '采购明细',
    payableLabel: '应付金额',
    paidLabel: '本次付款',
    submitText: '保存订单',
    apiEndpoint: '/purchase-orders',
  ),
  purchase(
    code: 'purchase',
    name: '采购入库',
    title: '新建采购入库',
    icon: Icons.shopping_cart,
    primaryColor: Color(0xFF1976D2),
    requiresPartner: true,
    requiresWarehouse: true,
    requiresAmount: false,
    partnerLabel: '供应商',
    warehouseLabel: '入库仓库',
    itemsLabel: '入库明细',
    payableLabel: null,
    paidLabel: null,
    submitText: '确认入库',
    apiEndpoint: '/purchase-in',
  ),
  saleOrder(
    code: 'sale_order',
    name: '销售订单',
    title: '新建销售订单',
    icon: Icons.point_of_sale,
    primaryColor: Color(0xFF9C27B0),
    requiresPartner: true,
    requiresWarehouse: true,
    requiresAmount: true,
    partnerLabel: '客户',
    warehouseLabel: '出库仓库',
    itemsLabel: '销售明细',
    payableLabel: '应收金额',
    paidLabel: '本次收款',
    submitText: '保存订单',
    apiEndpoint: '/sale-orders',
  ),
  sales(
    code: 'sales',
    name: '销售出库',
    title: '新建销售出库',
    icon: Icons.point_of_sale,
    primaryColor: Color(0xFF7B1FA2),
    requiresPartner: true,
    requiresWarehouse: true,
    requiresAmount: false,
    partnerLabel: '客户',
    warehouseLabel: '出库仓库',
    itemsLabel: '出库明细',
    payableLabel: null,
    paidLabel: null,
    submitText: '确认出库',
    apiEndpoint: '/sale-out',
  ),
  retailSale(
    code: 'retail_sale',
    name: '零售出库',
    title: '新建零售单',
    icon: Icons.store,
    primaryColor: Color(0xFF7B1FA2),
    requiresPartner: false,
    requiresWarehouse: true,
    requiresAmount: true,
    partnerLabel: null,
    warehouseLabel: '出库仓库',
    itemsLabel: '零售明细',
    payableLabel: '应收金额',
    paidLabel: '本次收款',
    submitText: '确认交易',
    apiEndpoint: '/retail-sales',
  ),
  transfer(
    code: 'transfer',
    name: '调拨单',
    title: '新建调拨单',
    icon: Icons.swap_horiz,
    primaryColor: Color(0xFFFF9800),
    requiresPartner: false,
    requiresWarehouse: true,
    requiresAmount: false,
    partnerLabel: null,
    warehouseLabel: '调出仓库',
    itemsLabel: '调拨明细',
    payableLabel: null,
    paidLabel: null,
    submitText: '确认调拨',
    apiEndpoint: '/transfers',
  ),
  stockCheck(
    code: 'stock_check',
    name: '盘点单',
    title: '新建盘点单',
    icon: Icons.inventory_2,
    primaryColor: Color(0xFF4CAF50),
    requiresPartner: false,
    requiresWarehouse: true,
    requiresAmount: false,
    partnerLabel: null,
    warehouseLabel: '盘点仓库',
    itemsLabel: '盘点明细',
    payableLabel: null,
    paidLabel: null,
    submitText: '开始盘点',
    apiEndpoint: '/stock-checks',
  ),
  stockIn(
    code: 'stock_in',
    name: '其他入库',
    title: '新建其他入库',
    icon: Icons.arrow_downward,
    primaryColor: Color(0xFF4CAF50),
    requiresPartner: false,
    requiresWarehouse: true,
    requiresAmount: false,
    partnerLabel: null,
    warehouseLabel: '入库仓库',
    itemsLabel: '入库明细',
    payableLabel: null,
    paidLabel: null,
    submitText: '确认入库',
    apiEndpoint: '/stock-in',
  ),
  stockOut(
    code: 'stock_out',
    name: '其他出库',
    title: '新建其他出库',
    icon: Icons.arrow_upward,
    primaryColor: Color(0xFFF44336),
    requiresPartner: false,
    requiresWarehouse: true,
    requiresAmount: false,
    partnerLabel: null,
    warehouseLabel: '出库仓库',
    itemsLabel: '出库明细',
    payableLabel: null,
    paidLabel: null,
    submitText: '确认出库',
    apiEndpoint: '/stock-out',
  );

  final String code;
  final String name;
  final String title;
  final IconData icon;
  final Color primaryColor;
  final bool requiresPartner;
  final bool requiresWarehouse;
  final bool requiresAmount;
  final String? partnerLabel;
  final String warehouseLabel;
  final String itemsLabel;
  final String? payableLabel;
  final String? paidLabel;
  final String submitText;
  final String apiEndpoint;

  const BillType({
    required this.code,
    required this.name,
    required this.title,
    required this.icon,
    required this.primaryColor,
    required this.requiresPartner,
    required this.requiresWarehouse,
    required this.requiresAmount,
    required this.partnerLabel,
    required this.warehouseLabel,
    required this.itemsLabel,
    required this.payableLabel,
    required this.paidLabel,
    required this.submitText,
    required this.apiEndpoint,
  });
}
